/*
 * OPC UA Web API
 *
 * Provides simple HTTPS based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 1.05.4
 * Contact: office@opcfoundation.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Opc.Ua.WebApi.Model;
using Opc.Ua.WebApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Opc.Ua.WebApi.Test.Model
{
    /// <summary>
    ///  Class for testing ActionMethodDataType
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ActionMethodDataTypeTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ActionMethodDataType
        //private ActionMethodDataType instance;

        public ActionMethodDataTypeTests()
        {
            // TODO uncomment below to create an instance of ActionMethodDataType
            //instance = new ActionMethodDataType();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ActionMethodDataType
        /// </summary>
        [Fact]
        public void ActionMethodDataTypeInstanceTest()
        {
            // TODO uncomment below to test "IsType" ActionMethodDataType
            //Assert.IsType<ActionMethodDataType>(instance);
        }

        /// <summary>
        /// Test the property 'ObjectId'
        /// </summary>
        [Fact]
        public void ObjectIdTest()
        {
            // TODO unit test for the property 'ObjectId'
        }

        /// <summary>
        /// Test the property 'MethodId'
        /// </summary>
        [Fact]
        public void MethodIdTest()
        {
            // TODO unit test for the property 'MethodId'
        }
    }
}
