/*
 * OPC UA Web API
 *
 * Provides simple HTTPS based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 1.05.4
 * Contact: office@opcfoundation.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Opc.Ua.WebApi.Model;
using Opc.Ua.WebApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Opc.Ua.WebApi.Test.Model
{
    /// <summary>
    ///  Class for testing ActionTargetDataType
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ActionTargetDataTypeTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ActionTargetDataType
        //private ActionTargetDataType instance;

        public ActionTargetDataTypeTests()
        {
            // TODO uncomment below to create an instance of ActionTargetDataType
            //instance = new ActionTargetDataType();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ActionTargetDataType
        /// </summary>
        [Fact]
        public void ActionTargetDataTypeInstanceTest()
        {
            // TODO uncomment below to test "IsType" ActionTargetDataType
            //Assert.IsType<ActionTargetDataType>(instance);
        }

        /// <summary>
        /// Test the property 'ActionTargetId'
        /// </summary>
        [Fact]
        public void ActionTargetIdTest()
        {
            // TODO unit test for the property 'ActionTargetId'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
    }
}
