/*
 * OPC UA Web API
 *
 * Provides simple HTTPS based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 1.05.4
 * Contact: office@opcfoundation.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Opc.Ua.WebApi.Model;
using Opc.Ua.WebApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Opc.Ua.WebApi.Test.Model
{
    /// <summary>
    ///  Class for testing DataValue
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DataValueTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DataValue
        //private DataValue instance;

        public DataValueTests()
        {
            // TODO uncomment below to create an instance of DataValue
            //instance = new DataValue();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DataValue
        /// </summary>
        [Fact]
        public void DataValueInstanceTest()
        {
            // TODO uncomment below to test "IsType" DataValue
            //Assert.IsType<DataValue>(instance);
        }

        /// <summary>
        /// Test the property 'UaType'
        /// </summary>
        [Fact]
        public void UaTypeTest()
        {
            // TODO unit test for the property 'UaType'
        }

        /// <summary>
        /// Test the property 'Value'
        /// </summary>
        [Fact]
        public void ValueTest()
        {
            // TODO unit test for the property 'Value'
        }

        /// <summary>
        /// Test the property 'Dimensions'
        /// </summary>
        [Fact]
        public void DimensionsTest()
        {
            // TODO unit test for the property 'Dimensions'
        }

        /// <summary>
        /// Test the property 'StatusCode'
        /// </summary>
        [Fact]
        public void StatusCodeTest()
        {
            // TODO unit test for the property 'StatusCode'
        }

        /// <summary>
        /// Test the property 'SourceTimestamp'
        /// </summary>
        [Fact]
        public void SourceTimestampTest()
        {
            // TODO unit test for the property 'SourceTimestamp'
        }

        /// <summary>
        /// Test the property 'SourcePicoseconds'
        /// </summary>
        [Fact]
        public void SourcePicosecondsTest()
        {
            // TODO unit test for the property 'SourcePicoseconds'
        }

        /// <summary>
        /// Test the property 'ServerTimestamp'
        /// </summary>
        [Fact]
        public void ServerTimestampTest()
        {
            // TODO unit test for the property 'ServerTimestamp'
        }

        /// <summary>
        /// Test the property 'ServerPicoseconds'
        /// </summary>
        [Fact]
        public void ServerPicosecondsTest()
        {
            // TODO unit test for the property 'ServerPicoseconds'
        }
    }
}
