/*
 * OPC UA Web API
 *
 * Provides simple HTTPS based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 1.05.4
 * Contact: office@opcfoundation.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Opc.Ua.WebApi.Model;
using Opc.Ua.WebApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Opc.Ua.WebApi.Test.Model
{
    /// <summary>
    ///  Class for testing ExtensionObject
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ExtensionObjectTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ExtensionObject
        //private ExtensionObject instance;

        public ExtensionObjectTests()
        {
            // TODO uncomment below to create an instance of ExtensionObject
            //instance = new ExtensionObject();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ExtensionObject
        /// </summary>
        [Fact]
        public void ExtensionObjectInstanceTest()
        {
            // TODO uncomment below to test "IsType" ExtensionObject
            //Assert.IsType<ExtensionObject>(instance);
        }

        /// <summary>
        /// Test the property 'UaTypeId'
        /// </summary>
        [Fact]
        public void UaTypeIdTest()
        {
            // TODO unit test for the property 'UaTypeId'
        }

        /// <summary>
        /// Test the property 'UaEncoding'
        /// </summary>
        [Fact]
        public void UaEncodingTest()
        {
            // TODO unit test for the property 'UaEncoding'
        }

        /// <summary>
        /// Test the property 'UaBody'
        /// </summary>
        [Fact]
        public void UaBodyTest()
        {
            // TODO unit test for the property 'UaBody'
        }
    }
}
