/*
 * OPC UA Web API
 *
 * Provides simple HTTPS based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 1.05.4
 * Contact: office@opcfoundation.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Opc.Ua.WebApi.Model;
using Opc.Ua.WebApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Opc.Ua.WebApi.Test.Model
{
    /// <summary>
    ///  Class for testing HistoryUpdateType
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class HistoryUpdateTypeTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for HistoryUpdateType
        //private HistoryUpdateType instance;

        public HistoryUpdateTypeTests()
        {
            // TODO uncomment below to create an instance of HistoryUpdateType
            //instance = new HistoryUpdateType();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of HistoryUpdateType
        /// </summary>
        [Fact]
        public void HistoryUpdateTypeInstanceTest()
        {
            // TODO uncomment below to test "IsType" HistoryUpdateType
            //Assert.IsType<HistoryUpdateType>(instance);
        }
    }
}
