/*
 * OPC UA Web API
 *
 * Provides simple HTTPS based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 1.05.4
 * Contact: office@opcfoundation.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Opc.Ua.WebApi.Model;
using Opc.Ua.WebApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Opc.Ua.WebApi.Test.Model
{
    /// <summary>
    ///  Class for testing JsonDataSetMessageContentMaskBits
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class JsonDataSetMessageContentMaskBitsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for JsonDataSetMessageContentMaskBits
        //private JsonDataSetMessageContentMaskBits instance;

        public JsonDataSetMessageContentMaskBitsTests()
        {
            // TODO uncomment below to create an instance of JsonDataSetMessageContentMaskBits
            //instance = new JsonDataSetMessageContentMaskBits();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of JsonDataSetMessageContentMaskBits
        /// </summary>
        [Fact]
        public void JsonDataSetMessageContentMaskBitsInstanceTest()
        {
            // TODO uncomment below to test "IsType" JsonDataSetMessageContentMaskBits
            //Assert.IsType<JsonDataSetMessageContentMaskBits>(instance);
        }
    }
}
