/*
 * OPC UA Web API
 *
 * Provides simple HTTPS based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 1.05.4
 * Contact: office@opcfoundation.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Opc.Ua.WebApi.Model;
using Opc.Ua.WebApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Opc.Ua.WebApi.Test.Model
{
    /// <summary>
    ///  Class for testing JsonDataSetMessage
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class JsonDataSetMessageTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for JsonDataSetMessage
        //private JsonDataSetMessage instance;

        public JsonDataSetMessageTests()
        {
            // TODO uncomment below to create an instance of JsonDataSetMessage
            //instance = new JsonDataSetMessage();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of JsonDataSetMessage
        /// </summary>
        [Fact]
        public void JsonDataSetMessageInstanceTest()
        {
            // TODO uncomment below to test "IsType" JsonDataSetMessage
            //Assert.IsType<JsonDataSetMessage>(instance);
        }

        /// <summary>
        /// Test the property 'DataSetWriterId'
        /// </summary>
        [Fact]
        public void DataSetWriterIdTest()
        {
            // TODO unit test for the property 'DataSetWriterId'
        }

        /// <summary>
        /// Test the property 'DataSetWriterName'
        /// </summary>
        [Fact]
        public void DataSetWriterNameTest()
        {
            // TODO unit test for the property 'DataSetWriterName'
        }

        /// <summary>
        /// Test the property 'PublisherId'
        /// </summary>
        [Fact]
        public void PublisherIdTest()
        {
            // TODO unit test for the property 'PublisherId'
        }

        /// <summary>
        /// Test the property 'WriterGroupName'
        /// </summary>
        [Fact]
        public void WriterGroupNameTest()
        {
            // TODO unit test for the property 'WriterGroupName'
        }

        /// <summary>
        /// Test the property 'SequenceNumber'
        /// </summary>
        [Fact]
        public void SequenceNumberTest()
        {
            // TODO unit test for the property 'SequenceNumber'
        }

        /// <summary>
        /// Test the property 'MetaDataVersion'
        /// </summary>
        [Fact]
        public void MetaDataVersionTest()
        {
            // TODO unit test for the property 'MetaDataVersion'
        }

        /// <summary>
        /// Test the property 'MinorVersion'
        /// </summary>
        [Fact]
        public void MinorVersionTest()
        {
            // TODO unit test for the property 'MinorVersion'
        }

        /// <summary>
        /// Test the property 'Timestamp'
        /// </summary>
        [Fact]
        public void TimestampTest()
        {
            // TODO unit test for the property 'Timestamp'
        }

        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }

        /// <summary>
        /// Test the property 'MessageType'
        /// </summary>
        [Fact]
        public void MessageTypeTest()
        {
            // TODO unit test for the property 'MessageType'
        }

        /// <summary>
        /// Test the property 'Payload'
        /// </summary>
        [Fact]
        public void PayloadTest()
        {
            // TODO unit test for the property 'Payload'
        }
    }
}
