/*
 * OPC UA Web API
 *
 * Provides simple HTTPS based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 1.05.4
 * Contact: office@opcfoundation.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Opc.Ua.WebApi.Model;
using Opc.Ua.WebApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Opc.Ua.WebApi.Test.Model
{
    /// <summary>
    ///  Class for testing JsonStatusMessage
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class JsonStatusMessageTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for JsonStatusMessage
        //private JsonStatusMessage instance;

        public JsonStatusMessageTests()
        {
            // TODO uncomment below to create an instance of JsonStatusMessage
            //instance = new JsonStatusMessage();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of JsonStatusMessage
        /// </summary>
        [Fact]
        public void JsonStatusMessageInstanceTest()
        {
            // TODO uncomment below to test "IsType" JsonStatusMessage
            //Assert.IsType<JsonStatusMessage>(instance);
        }

        /// <summary>
        /// Test the property 'MessageId'
        /// </summary>
        [Fact]
        public void MessageIdTest()
        {
            // TODO unit test for the property 'MessageId'
        }

        /// <summary>
        /// Test the property 'MessageType'
        /// </summary>
        [Fact]
        public void MessageTypeTest()
        {
            // TODO unit test for the property 'MessageType'
        }

        /// <summary>
        /// Test the property 'PublisherId'
        /// </summary>
        [Fact]
        public void PublisherIdTest()
        {
            // TODO unit test for the property 'PublisherId'
        }

        /// <summary>
        /// Test the property 'Timestamp'
        /// </summary>
        [Fact]
        public void TimestampTest()
        {
            // TODO unit test for the property 'Timestamp'
        }

        /// <summary>
        /// Test the property 'IsCyclic'
        /// </summary>
        [Fact]
        public void IsCyclicTest()
        {
            // TODO unit test for the property 'IsCyclic'
        }

        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }

        /// <summary>
        /// Test the property 'NextReportTime'
        /// </summary>
        [Fact]
        public void NextReportTimeTest()
        {
            // TODO unit test for the property 'NextReportTime'
        }
    }
}
