/*
 * OPC UA Web API
 *
 * Provides simple HTTPS based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 1.05.4
 * Contact: office@opcfoundation.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Opc.Ua.WebApi.Model;
using Opc.Ua.WebApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Opc.Ua.WebApi.Test.Model
{
    /// <summary>
    ///  Class for testing JsonNetworkMessage
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class JsonNetworkMessageTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for JsonNetworkMessage
        //private JsonNetworkMessage instance;

        public JsonNetworkMessageTests()
        {
            // TODO uncomment below to create an instance of JsonNetworkMessage
            //instance = new JsonNetworkMessage();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of JsonNetworkMessage
        /// </summary>
        [Fact]
        public void JsonNetworkMessageInstanceTest()
        {
            // TODO uncomment below to test "IsType" JsonNetworkMessage
            //Assert.IsType<JsonNetworkMessage>(instance);
        }

        /// <summary>
        /// Test the property 'MessageId'
        /// </summary>
        [Fact]
        public void MessageIdTest()
        {
            // TODO unit test for the property 'MessageId'
        }

        /// <summary>
        /// Test the property 'MessageType'
        /// </summary>
        [Fact]
        public void MessageTypeTest()
        {
            // TODO unit test for the property 'MessageType'
        }

        /// <summary>
        /// Test the property 'PublisherId'
        /// </summary>
        [Fact]
        public void PublisherIdTest()
        {
            // TODO unit test for the property 'PublisherId'
        }

        /// <summary>
        /// Test the property 'WriterGroupName'
        /// </summary>
        [Fact]
        public void WriterGroupNameTest()
        {
            // TODO unit test for the property 'WriterGroupName'
        }

        /// <summary>
        /// Test the property 'DataSetClassId'
        /// </summary>
        [Fact]
        public void DataSetClassIdTest()
        {
            // TODO unit test for the property 'DataSetClassId'
        }

        /// <summary>
        /// Test the property 'Messages'
        /// </summary>
        [Fact]
        public void MessagesTest()
        {
            // TODO unit test for the property 'Messages'
        }
    }
}
