/*
 * OPC UA Web API
 *
 * Provides simple HTTPS based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 1.05.4
 * Contact: office@opcfoundation.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Opc.Ua.WebApi.Model;
using Opc.Ua.WebApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Opc.Ua.WebApi.Test.Model
{
    /// <summary>
    ///  Class for testing JsonActionMetaDataMessage
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class JsonActionMetaDataMessageTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for JsonActionMetaDataMessage
        //private JsonActionMetaDataMessage instance;

        public JsonActionMetaDataMessageTests()
        {
            // TODO uncomment below to create an instance of JsonActionMetaDataMessage
            //instance = new JsonActionMetaDataMessage();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of JsonActionMetaDataMessage
        /// </summary>
        [Fact]
        public void JsonActionMetaDataMessageInstanceTest()
        {
            // TODO uncomment below to test "IsType" JsonActionMetaDataMessage
            //Assert.IsType<JsonActionMetaDataMessage>(instance);
        }

        /// <summary>
        /// Test the property 'MessageId'
        /// </summary>
        [Fact]
        public void MessageIdTest()
        {
            // TODO unit test for the property 'MessageId'
        }

        /// <summary>
        /// Test the property 'MessageType'
        /// </summary>
        [Fact]
        public void MessageTypeTest()
        {
            // TODO unit test for the property 'MessageType'
        }

        /// <summary>
        /// Test the property 'PublisherId'
        /// </summary>
        [Fact]
        public void PublisherIdTest()
        {
            // TODO unit test for the property 'PublisherId'
        }

        /// <summary>
        /// Test the property 'DataSetWriterId'
        /// </summary>
        [Fact]
        public void DataSetWriterIdTest()
        {
            // TODO unit test for the property 'DataSetWriterId'
        }

        /// <summary>
        /// Test the property 'DataSetWriterName'
        /// </summary>
        [Fact]
        public void DataSetWriterNameTest()
        {
            // TODO unit test for the property 'DataSetWriterName'
        }

        /// <summary>
        /// Test the property 'Timestamp'
        /// </summary>
        [Fact]
        public void TimestampTest()
        {
            // TODO unit test for the property 'Timestamp'
        }

        /// <summary>
        /// Test the property 'ActionTargets'
        /// </summary>
        [Fact]
        public void ActionTargetsTest()
        {
            // TODO unit test for the property 'ActionTargets'
        }

        /// <summary>
        /// Test the property 'Request'
        /// </summary>
        [Fact]
        public void RequestTest()
        {
            // TODO unit test for the property 'Request'
        }

        /// <summary>
        /// Test the property 'Response'
        /// </summary>
        [Fact]
        public void ResponseTest()
        {
            // TODO unit test for the property 'Response'
        }

        /// <summary>
        /// Test the property 'ActionMethods'
        /// </summary>
        [Fact]
        public void ActionMethodsTest()
        {
            // TODO unit test for the property 'ActionMethods'
        }
    }
}
