/*
 * OPC UA Web API
 *
 * Provides simple HTTPS based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 1.05.4
 * Contact: office@opcfoundation.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Opc.Ua.WebApi.Model;
using Opc.Ua.WebApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Opc.Ua.WebApi.Test.Model
{
    /// <summary>
    ///  Class for testing JsonApplicationDescriptionMessage
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class JsonApplicationDescriptionMessageTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for JsonApplicationDescriptionMessage
        //private JsonApplicationDescriptionMessage instance;

        public JsonApplicationDescriptionMessageTests()
        {
            // TODO uncomment below to create an instance of JsonApplicationDescriptionMessage
            //instance = new JsonApplicationDescriptionMessage();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of JsonApplicationDescriptionMessage
        /// </summary>
        [Fact]
        public void JsonApplicationDescriptionMessageInstanceTest()
        {
            // TODO uncomment below to test "IsType" JsonApplicationDescriptionMessage
            //Assert.IsType<JsonApplicationDescriptionMessage>(instance);
        }

        /// <summary>
        /// Test the property 'MessageId'
        /// </summary>
        [Fact]
        public void MessageIdTest()
        {
            // TODO unit test for the property 'MessageId'
        }

        /// <summary>
        /// Test the property 'MessageType'
        /// </summary>
        [Fact]
        public void MessageTypeTest()
        {
            // TODO unit test for the property 'MessageType'
        }

        /// <summary>
        /// Test the property 'PublisherId'
        /// </summary>
        [Fact]
        public void PublisherIdTest()
        {
            // TODO unit test for the property 'PublisherId'
        }

        /// <summary>
        /// Test the property 'Timestamp'
        /// </summary>
        [Fact]
        public void TimestampTest()
        {
            // TODO unit test for the property 'Timestamp'
        }

        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }

        /// <summary>
        /// Test the property 'ServerCapabilities'
        /// </summary>
        [Fact]
        public void ServerCapabilitiesTest()
        {
            // TODO unit test for the property 'ServerCapabilities'
        }
    }
}
