/*
 * OPC UA Web API
 *
 * Provides simple HTTPS based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 1.05.4
 * Contact: office@opcfoundation.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Opc.Ua.WebApi.Model;
using Opc.Ua.WebApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Opc.Ua.WebApi.Test.Model
{
    /// <summary>
    ///  Class for testing PermissionTypeBits
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PermissionTypeBitsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PermissionTypeBits
        //private PermissionTypeBits instance;

        public PermissionTypeBitsTests()
        {
            // TODO uncomment below to create an instance of PermissionTypeBits
            //instance = new PermissionTypeBits();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PermissionTypeBits
        /// </summary>
        [Fact]
        public void PermissionTypeBitsInstanceTest()
        {
            // TODO uncomment below to test "IsType" PermissionTypeBits
            //Assert.IsType<PermissionTypeBits>(instance);
        }
    }
}
