/*
 * OPC UA Web API
 *
 * Provides simple HTTPS based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 1.05.4
 * Contact: office@opcfoundation.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Opc.Ua.WebApi.Model;
using Opc.Ua.WebApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Opc.Ua.WebApi.Test.Model
{
    /// <summary>
    ///  Class for testing ReadEventDetails2
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ReadEventDetails2Tests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ReadEventDetails2
        //private ReadEventDetails2 instance;

        public ReadEventDetails2Tests()
        {
            // TODO uncomment below to create an instance of ReadEventDetails2
            //instance = new ReadEventDetails2();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ReadEventDetails2
        /// </summary>
        [Fact]
        public void ReadEventDetails2InstanceTest()
        {
            // TODO uncomment below to test "IsType" ReadEventDetails2
            //Assert.IsType<ReadEventDetails2>(instance);
        }

        /// <summary>
        /// Test the property 'ReadModified'
        /// </summary>
        [Fact]
        public void ReadModifiedTest()
        {
            // TODO unit test for the property 'ReadModified'
        }

        /// <summary>
        /// Test the property 'NumValuesPerNode'
        /// </summary>
        [Fact]
        public void NumValuesPerNodeTest()
        {
            // TODO unit test for the property 'NumValuesPerNode'
        }

        /// <summary>
        /// Test the property 'StartTime'
        /// </summary>
        [Fact]
        public void StartTimeTest()
        {
            // TODO unit test for the property 'StartTime'
        }

        /// <summary>
        /// Test the property 'EndTime'
        /// </summary>
        [Fact]
        public void EndTimeTest()
        {
            // TODO unit test for the property 'EndTime'
        }

        /// <summary>
        /// Test the property 'Filter'
        /// </summary>
        [Fact]
        public void FilterTest()
        {
            // TODO unit test for the property 'Filter'
        }
    }
}
