/*
 * OPC UA Web API
 *
 * Provides simple HTTPS based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 1.05.4
 * Contact: office@opcfoundation.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Opc.Ua.WebApi.Client.OpenAPIDateConverter;

namespace Opc.Ua.WebApi.Model
{
    /// <summary>
    /// [Link to specification](https://reference.opcfoundation.org/v105/Core/docs/Part14/6.2.3/#6.2.3.10.3).
    /// </summary>
    [DataContract(Name = "ActionTargetDataType")]
    public partial class ActionTargetDataType : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ActionTargetDataType" /> class.
        /// </summary>
        /// <param name="actionTargetId">actionTargetId (default to 0).</param>
        /// <param name="name">name.</param>
        /// <param name="description">description.</param>
        public ActionTargetDataType(int actionTargetId = 0, string name = default(string), LocalizedText description = default(LocalizedText))
        {
            this.ActionTargetId = actionTargetId;
            this.Name = name;
            this.Description = description;
        }

        /// <summary>
        /// Gets or Sets ActionTargetId
        /// </summary>
        [DataMember(Name = "ActionTargetId", EmitDefaultValue = false)]
        public int ActionTargetId { get; set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [DataMember(Name = "Name", EmitDefaultValue = false)]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets Description
        /// </summary>
        [DataMember(Name = "Description", EmitDefaultValue = false)]
        public LocalizedText Description { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ActionTargetDataType {\n");
            sb.Append("  ActionTargetId: ").Append(ActionTargetId).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // ActionTargetId (int) maximum
            if (this.ActionTargetId > (int)65535)
            {
                yield return new ValidationResult("Invalid value for ActionTargetId, must be a value less than or equal to 65535.", new [] { "ActionTargetId" });
            }

            // ActionTargetId (int) minimum
            if (this.ActionTargetId < (int)0)
            {
                yield return new ValidationResult("Invalid value for ActionTargetId, must be a value greater than or equal to 0.", new [] { "ActionTargetId" });
            }

            yield break;
        }
    }

}
