/*
 * OPC UA Web API
 *
 * Provides simple HTTPS based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 1.05.4
 * Contact: office@opcfoundation.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Opc.Ua.WebApi.Client.FileParameter;
using OpenAPIDateConverter = Opc.Ua.WebApi.Client.OpenAPIDateConverter;

namespace Opc.Ua.WebApi.Model
{
    /// <summary>
    /// [Link to specification](https://reference.opcfoundation.org/v105/Core/docs/Part4/5.7.3/#5.7.3.2).
    /// </summary>
    [DataContract(Name = "ActivateSessionRequest")]
    public partial class ActivateSessionRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ActivateSessionRequest" /> class.
        /// </summary>
        /// <param name="requestHeader">requestHeader.</param>
        /// <param name="clientSignature">clientSignature.</param>
        /// <param name="clientSoftwareCertificates">clientSoftwareCertificates.</param>
        /// <param name="localeIds">localeIds.</param>
        /// <param name="userIdentityToken">userIdentityToken.</param>
        /// <param name="userTokenSignature">userTokenSignature.</param>
        public ActivateSessionRequest(RequestHeader requestHeader = default, SignatureData clientSignature = default, List<SignedSoftwareCertificate> clientSoftwareCertificates = default, List<string> localeIds = default, ExtensionObject userIdentityToken = default, SignatureData userTokenSignature = default)
        {
            this.RequestHeader = requestHeader;
            this.ClientSignature = clientSignature;
            this.ClientSoftwareCertificates = clientSoftwareCertificates;
            this.LocaleIds = localeIds;
            this.UserIdentityToken = userIdentityToken;
            this.UserTokenSignature = userTokenSignature;
        }

        /// <summary>
        /// Gets or Sets RequestHeader
        /// </summary>
        [DataMember(Name = "RequestHeader", EmitDefaultValue = false)]
        public RequestHeader RequestHeader { get; set; }

        /// <summary>
        /// Gets or Sets ClientSignature
        /// </summary>
        [DataMember(Name = "ClientSignature", EmitDefaultValue = false)]
        public SignatureData ClientSignature { get; set; }

        /// <summary>
        /// Gets or Sets ClientSoftwareCertificates
        /// </summary>
        [DataMember(Name = "ClientSoftwareCertificates", EmitDefaultValue = false)]
        public List<SignedSoftwareCertificate> ClientSoftwareCertificates { get; set; }

        /// <summary>
        /// Gets or Sets LocaleIds
        /// </summary>
        [DataMember(Name = "LocaleIds", EmitDefaultValue = false)]
        public List<string> LocaleIds { get; set; }

        /// <summary>
        /// Gets or Sets UserIdentityToken
        /// </summary>
        [DataMember(Name = "UserIdentityToken", EmitDefaultValue = false)]
        public ExtensionObject UserIdentityToken { get; set; }

        /// <summary>
        /// Gets or Sets UserTokenSignature
        /// </summary>
        [DataMember(Name = "UserTokenSignature", EmitDefaultValue = false)]
        public SignatureData UserTokenSignature { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ActivateSessionRequest {\n");
            sb.Append("  RequestHeader: ").Append(RequestHeader).Append("\n");
            sb.Append("  ClientSignature: ").Append(ClientSignature).Append("\n");
            sb.Append("  ClientSoftwareCertificates: ").Append(ClientSoftwareCertificates).Append("\n");
            sb.Append("  LocaleIds: ").Append(LocaleIds).Append("\n");
            sb.Append("  UserIdentityToken: ").Append(UserIdentityToken).Append("\n");
            sb.Append("  UserTokenSignature: ").Append(UserTokenSignature).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
