/*
 * OPC UA Web API
 *
 * Provides simple HTTPS based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 1.05.4
 * Contact: office@opcfoundation.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Opc.Ua.WebApi.Client.OpenAPIDateConverter;

namespace Opc.Ua.WebApi.Model
{
    /// <summary>
    /// BrokerDataSetReaderTransportDataType
    /// </summary>
    [DataContract(Name = "BrokerDataSetReaderTransportDataType")]
    public partial class BrokerDataSetReaderTransportDataType : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="BrokerDataSetReaderTransportDataType" /> class.
        /// </summary>
        /// <param name="queueName">queueName.</param>
        /// <param name="resourceUri">resourceUri.</param>
        /// <param name="authenticationProfileUri">authenticationProfileUri.</param>
        /// <param name="requestedDeliveryGuarantee">requestedDeliveryGuarantee.</param>
        /// <param name="metaDataQueueName">metaDataQueueName.</param>
        public BrokerDataSetReaderTransportDataType(string queueName = default(string), string resourceUri = default(string), string authenticationProfileUri = default(string), int requestedDeliveryGuarantee = default(int), string metaDataQueueName = default(string))
        {
            this.QueueName = queueName;
            this.ResourceUri = resourceUri;
            this.AuthenticationProfileUri = authenticationProfileUri;
            this.RequestedDeliveryGuarantee = requestedDeliveryGuarantee;
            this.MetaDataQueueName = metaDataQueueName;
        }

        /// <summary>
        /// Gets or Sets QueueName
        /// </summary>
        [DataMember(Name = "QueueName", EmitDefaultValue = false)]
        public string QueueName { get; set; }

        /// <summary>
        /// Gets or Sets ResourceUri
        /// </summary>
        [DataMember(Name = "ResourceUri", EmitDefaultValue = false)]
        public string ResourceUri { get; set; }

        /// <summary>
        /// Gets or Sets AuthenticationProfileUri
        /// </summary>
        [DataMember(Name = "AuthenticationProfileUri", EmitDefaultValue = false)]
        public string AuthenticationProfileUri { get; set; }

        /// <summary>
        /// Gets or Sets RequestedDeliveryGuarantee
        /// </summary>
        [DataMember(Name = "RequestedDeliveryGuarantee", EmitDefaultValue = false)]
        public int RequestedDeliveryGuarantee { get; set; }

        /// <summary>
        /// Gets or Sets MetaDataQueueName
        /// </summary>
        [DataMember(Name = "MetaDataQueueName", EmitDefaultValue = false)]
        public string MetaDataQueueName { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class BrokerDataSetReaderTransportDataType {\n");
            sb.Append("  QueueName: ").Append(QueueName).Append("\n");
            sb.Append("  ResourceUri: ").Append(ResourceUri).Append("\n");
            sb.Append("  AuthenticationProfileUri: ").Append(AuthenticationProfileUri).Append("\n");
            sb.Append("  RequestedDeliveryGuarantee: ").Append(RequestedDeliveryGuarantee).Append("\n");
            sb.Append("  MetaDataQueueName: ").Append(MetaDataQueueName).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
