/*
 * OPC UA Web API
 *
 * Provides simple HTTPS based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 1.05.4
 * Contact: office@opcfoundation.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Opc.Ua.WebApi.Client.OpenAPIDateConverter;

namespace Opc.Ua.WebApi.Model
{
    /// <summary>
    /// [Link to specification](https://reference.opcfoundation.org/v105/Core/docs/Part14/6.2.4/#6.2.4.2).
    /// </summary>
    /// <value>[Link to specification](https://reference.opcfoundation.org/v105/Core/docs/Part14/6.2.4/#6.2.4.2).</value>
    public enum DataSetFieldContentMaskBits
    {
        /// <summary>
        /// Enum StatusCode for value: 1
        /// </summary>
        StatusCode = 1,

        /// <summary>
        /// Enum SourceTimestamp for value: 2
        /// </summary>
        SourceTimestamp = 2,

        /// <summary>
        /// Enum ServerTimestamp for value: 4
        /// </summary>
        ServerTimestamp = 4,

        /// <summary>
        /// Enum SourcePicoSeconds for value: 8
        /// </summary>
        SourcePicoSeconds = 8,

        /// <summary>
        /// Enum ServerPicoSeconds for value: 16
        /// </summary>
        ServerPicoSeconds = 16,

        /// <summary>
        /// Enum RawData for value: 32
        /// </summary>
        RawData = 32
    }

}
