/*
 * OPC UA Web API
 *
 * Provides simple HTTPS based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 1.05.4
 * Contact: office@opcfoundation.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Opc.Ua.WebApi.Client.OpenAPIDateConverter;

namespace Opc.Ua.WebApi.Model
{
    /// <summary>
    /// ExtensionObject
    /// </summary>
    [DataContract(Name = "ExtensionObject")]
    public partial class ExtensionObject : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ExtensionObject" /> class.
        /// </summary>
        /// <param name="uaTypeId">uaTypeId.</param>
        /// <param name="uaEncoding">uaEncoding.</param>
        /// <param name="uaBody">uaBody.</param>
        public ExtensionObject(string uaTypeId = default(string), int uaEncoding = default(int), byte[] uaBody = default(byte[]))
        {
            this.UaTypeId = uaTypeId;
            this.UaEncoding = uaEncoding;
            this.UaBody = uaBody;
        }

        /// <summary>
        /// Gets or Sets UaTypeId
        /// </summary>
        [DataMember(Name = "UaTypeId", EmitDefaultValue = false)]
        public string UaTypeId { get; set; }

        /// <summary>
        /// Gets or Sets UaEncoding
        /// </summary>
        [DataMember(Name = "UaEncoding", EmitDefaultValue = false)]
        public int UaEncoding { get; set; }

        /// <summary>
        /// Gets or Sets UaBody
        /// </summary>
        [DataMember(Name = "UaBody", EmitDefaultValue = false)]
        public byte[] UaBody { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ExtensionObject {\n");
            sb.Append("  UaTypeId: ").Append(UaTypeId).Append("\n");
            sb.Append("  UaEncoding: ").Append(UaEncoding).Append("\n");
            sb.Append("  UaBody: ").Append(UaBody).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // UaEncoding (int) maximum
            if (this.UaEncoding > (int)255)
            {
                yield return new ValidationResult("Invalid value for UaEncoding, must be a value less than or equal to 255.", new [] { "UaEncoding" });
            }

            // UaEncoding (int) minimum
            if (this.UaEncoding < (int)0)
            {
                yield return new ValidationResult("Invalid value for UaEncoding, must be a value greater than or equal to 0.", new [] { "UaEncoding" });
            }

            yield break;
        }
    }

}
