/*
 * OPC UA Web API
 *
 * Provides simple HTTPS based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 1.05.4
 * Contact: office@opcfoundation.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Opc.Ua.WebApi.Client.OpenAPIDateConverter;

namespace Opc.Ua.WebApi.Model
{
    /// <summary>
    /// [Link to specification](https://reference.opcfoundation.org/v105/Core/docs/Part11/6.6.3).
    /// </summary>
    [DataContract(Name = "HistoryModifiedData")]
    public partial class HistoryModifiedData : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="HistoryModifiedData" /> class.
        /// </summary>
        /// <param name="modificationInfos">modificationInfos.</param>
        /// <param name="dataValues">dataValues.</param>
        public HistoryModifiedData(List<ModificationInfo> modificationInfos = default(List<ModificationInfo>), List<DataValue> dataValues = default(List<DataValue>))
        {
            this.ModificationInfos = modificationInfos;
            this.DataValues = dataValues;
        }

        /// <summary>
        /// Gets or Sets ModificationInfos
        /// </summary>
        [DataMember(Name = "ModificationInfos", EmitDefaultValue = false)]
        public List<ModificationInfo> ModificationInfos { get; set; }

        /// <summary>
        /// Gets or Sets DataValues
        /// </summary>
        [DataMember(Name = "DataValues", EmitDefaultValue = false)]
        public List<DataValue> DataValues { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class HistoryModifiedData {\n");
            sb.Append("  ModificationInfos: ").Append(ModificationInfos).Append("\n");
            sb.Append("  DataValues: ").Append(DataValues).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
