/*
 * OPC UA Web API
 *
 * Provides simple HTTPS based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 1.05.4
 * Contact: office@opcfoundation.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Opc.Ua.WebApi.Client.OpenAPIDateConverter;

namespace Opc.Ua.WebApi.Model
{
    /// <summary>
    /// [Link to specification](https://reference.opcfoundation.org/v105/Core/docs/Part14/6.3.2/#6.3.2.1.2).
    /// </summary>
    [DataContract(Name = "JsonWriterGroupMessageDataType")]
    public partial class JsonWriterGroupMessageDataType : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="JsonWriterGroupMessageDataType" /> class.
        /// </summary>
        /// <param name="networkMessageContentMask">networkMessageContentMask (default to 0).</param>
        public JsonWriterGroupMessageDataType(long networkMessageContentMask = 0)
        {
            this.NetworkMessageContentMask = networkMessageContentMask;
        }

        /// <summary>
        /// Gets or Sets NetworkMessageContentMask
        /// </summary>
        [DataMember(Name = "NetworkMessageContentMask", EmitDefaultValue = false)]
        public long NetworkMessageContentMask { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class JsonWriterGroupMessageDataType {\n");
            sb.Append("  NetworkMessageContentMask: ").Append(NetworkMessageContentMask).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // NetworkMessageContentMask (long) maximum
            if (this.NetworkMessageContentMask > (long)4294967295)
            {
                yield return new ValidationResult("Invalid value for NetworkMessageContentMask, must be a value less than or equal to 4294967295.", new [] { "NetworkMessageContentMask" });
            }

            // NetworkMessageContentMask (long) minimum
            if (this.NetworkMessageContentMask < (long)0)
            {
                yield return new ValidationResult("Invalid value for NetworkMessageContentMask, must be a value greater than or equal to 0.", new [] { "NetworkMessageContentMask" });
            }

            yield break;
        }
    }

}
