/*
 * OPC UA Web API
 *
 * Provides simple HTTPS based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 1.05.4
 * Contact: office@opcfoundation.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Opc.Ua.WebApi.Client.OpenAPIDateConverter;

namespace Opc.Ua.WebApi.Model
{
    /// <summary>
    /// [Link to specification](https://reference.opcfoundation.org/v105/Core/docs/Part5/12.3.10).
    /// </summary>
    /// <value>[Link to specification](https://reference.opcfoundation.org/v105/Core/docs/Part5/12.3.10).</value>
    public enum MessageSecurityMode
    {
        /// <summary>
        /// Enum Invalid for value: 0
        /// </summary>
        Invalid = 0,

        /// <summary>
        /// Enum None for value: 1
        /// </summary>
        None = 1,

        /// <summary>
        /// Enum Sign for value: 2
        /// </summary>
        Sign = 2,

        /// <summary>
        /// Enum SignAndEncrypt for value: 3
        /// </summary>
        SignAndEncrypt = 3
    }

}
