/*
 * OPC UA Web API
 *
 * Provides simple HTTPS based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 1.05.4
 * Contact: office@opcfoundation.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Opc.Ua.WebApi.Client.FileParameter;
using OpenAPIDateConverter = Opc.Ua.WebApi.Client.OpenAPIDateConverter;

namespace Opc.Ua.WebApi.Model
{
    /// <summary>
    /// [Link to specification](https://reference.opcfoundation.org/v105/Core/docs/Part4/5.13.2/#5.13.2.2).
    /// </summary>
    [DataContract(Name = "MonitoredItemCreateRequest")]
    public partial class MonitoredItemCreateRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="MonitoredItemCreateRequest" /> class.
        /// </summary>
        /// <param name="itemToMonitor">itemToMonitor.</param>
        /// <param name="monitoringMode">[Link to specification](https://reference.opcfoundation.org/v105/Core/docs/Part4/7.23)..</param>
        /// <param name="requestedParameters">requestedParameters.</param>
        public MonitoredItemCreateRequest(ReadValueId itemToMonitor = default, int monitoringMode = default, MonitoringParameters requestedParameters = default)
        {
            this.ItemToMonitor = itemToMonitor;
            this.MonitoringMode = monitoringMode;
            this.RequestedParameters = requestedParameters;
        }

        /// <summary>
        /// Gets or Sets ItemToMonitor
        /// </summary>
        [DataMember(Name = "ItemToMonitor", EmitDefaultValue = false)]
        public ReadValueId ItemToMonitor { get; set; }

        /// <summary>
        /// [Link to specification](https://reference.opcfoundation.org/v105/Core/docs/Part4/7.23).
        /// </summary>
        /// <value>[Link to specification](https://reference.opcfoundation.org/v105/Core/docs/Part4/7.23).</value>
        [DataMember(Name = "MonitoringMode", EmitDefaultValue = false)]
        public int MonitoringMode { get; set; }

        /// <summary>
        /// Gets or Sets RequestedParameters
        /// </summary>
        [DataMember(Name = "RequestedParameters", EmitDefaultValue = false)]
        public MonitoringParameters RequestedParameters { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class MonitoredItemCreateRequest {\n");
            sb.Append("  ItemToMonitor: ").Append(ItemToMonitor).Append("\n");
            sb.Append("  MonitoringMode: ").Append(MonitoringMode).Append("\n");
            sb.Append("  RequestedParameters: ").Append(RequestedParameters).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
