/*
 * OPC UA Web API
 *
 * Provides simple HTTPS based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 1.05.4
 * Contact: office@opcfoundation.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Opc.Ua.WebApi.Client.FileParameter;
using OpenAPIDateConverter = Opc.Ua.WebApi.Client.OpenAPIDateConverter;

namespace Opc.Ua.WebApi.Model
{
    /// <summary>
    /// [Link to specification](https://reference.opcfoundation.org/v105/Core/docs/Part3/8.55).
    /// </summary>
    /// <value>[Link to specification](https://reference.opcfoundation.org/v105/Core/docs/Part3/8.55).</value>
    public enum PermissionTypeBits
    {
        /// <summary>
        /// Enum Browse for value: 1
        /// </summary>
        Browse = 1,

        /// <summary>
        /// Enum ReadRolePermissions for value: 2
        /// </summary>
        ReadRolePermissions = 2,

        /// <summary>
        /// Enum WriteAttribute for value: 4
        /// </summary>
        WriteAttribute = 4,

        /// <summary>
        /// Enum WriteRolePermissions for value: 8
        /// </summary>
        WriteRolePermissions = 8,

        /// <summary>
        /// Enum WriteHistorizing for value: 16
        /// </summary>
        WriteHistorizing = 16,

        /// <summary>
        /// Enum Read for value: 32
        /// </summary>
        Read = 32,

        /// <summary>
        /// Enum Write for value: 64
        /// </summary>
        Write = 64,

        /// <summary>
        /// Enum ReadHistory for value: 128
        /// </summary>
        ReadHistory = 128,

        /// <summary>
        /// Enum InsertHistory for value: 256
        /// </summary>
        InsertHistory = 256,

        /// <summary>
        /// Enum ModifyHistory for value: 512
        /// </summary>
        ModifyHistory = 512,

        /// <summary>
        /// Enum DeleteHistory for value: 1024
        /// </summary>
        DeleteHistory = 1024,

        /// <summary>
        /// Enum ReceiveEvents for value: 2048
        /// </summary>
        ReceiveEvents = 2048,

        /// <summary>
        /// Enum Call for value: 4096
        /// </summary>
        Call = 4096,

        /// <summary>
        /// Enum AddReference for value: 8192
        /// </summary>
        AddReference = 8192,

        /// <summary>
        /// Enum RemoveReference for value: 16384
        /// </summary>
        RemoveReference = 16384,

        /// <summary>
        /// Enum DeleteNode for value: 32768
        /// </summary>
        DeleteNode = 32768,

        /// <summary>
        /// Enum AddNode for value: 65536
        /// </summary>
        AddNode = 65536
    }

}
