/*
 * OPC UA Web API
 *
 * Provides simple HTTPS based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 1.05.4
 * Contact: office@opcfoundation.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Opc.Ua.WebApi.Client.OpenAPIDateConverter;

namespace Opc.Ua.WebApi.Model
{
    /// <summary>
    /// [Link to specification](https://reference.opcfoundation.org/v105/Core/docs/Part4/5.14.5/#5.14.5.2).
    /// </summary>
    [DataContract(Name = "PublishResponse")]
    public partial class PublishResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PublishResponse" /> class.
        /// </summary>
        /// <param name="responseHeader">responseHeader.</param>
        /// <param name="subscriptionId">subscriptionId (default to 0).</param>
        /// <param name="availableSequenceNumbers">availableSequenceNumbers.</param>
        /// <param name="moreNotifications">moreNotifications (default to false).</param>
        /// <param name="notificationMessage">notificationMessage.</param>
        /// <param name="results">results.</param>
        /// <param name="diagnosticInfos">diagnosticInfos.</param>
        public PublishResponse(ResponseHeader responseHeader = default(ResponseHeader), long subscriptionId = 0, List<long> availableSequenceNumbers = default(List<long>), bool moreNotifications = false, NotificationMessage notificationMessage = default(NotificationMessage), List<StatusCode> results = default(List<StatusCode>), List<DiagnosticInfo> diagnosticInfos = default(List<DiagnosticInfo>))
        {
            this.ResponseHeader = responseHeader;
            this.SubscriptionId = subscriptionId;
            this.AvailableSequenceNumbers = availableSequenceNumbers;
            this.MoreNotifications = moreNotifications;
            this.NotificationMessage = notificationMessage;
            this.Results = results;
            this.DiagnosticInfos = diagnosticInfos;
        }

        /// <summary>
        /// Gets or Sets ResponseHeader
        /// </summary>
        [DataMember(Name = "ResponseHeader", EmitDefaultValue = false)]
        public ResponseHeader ResponseHeader { get; set; }

        /// <summary>
        /// Gets or Sets SubscriptionId
        /// </summary>
        [DataMember(Name = "SubscriptionId", EmitDefaultValue = false)]
        public long SubscriptionId { get; set; }

        /// <summary>
        /// Gets or Sets AvailableSequenceNumbers
        /// </summary>
        [DataMember(Name = "AvailableSequenceNumbers", EmitDefaultValue = false)]
        public List<long> AvailableSequenceNumbers { get; set; }

        /// <summary>
        /// Gets or Sets MoreNotifications
        /// </summary>
        [DataMember(Name = "MoreNotifications", EmitDefaultValue = true)]
        public bool MoreNotifications { get; set; }

        /// <summary>
        /// Gets or Sets NotificationMessage
        /// </summary>
        [DataMember(Name = "NotificationMessage", EmitDefaultValue = false)]
        public NotificationMessage NotificationMessage { get; set; }

        /// <summary>
        /// Gets or Sets Results
        /// </summary>
        [DataMember(Name = "Results", EmitDefaultValue = false)]
        public List<StatusCode> Results { get; set; }

        /// <summary>
        /// Gets or Sets DiagnosticInfos
        /// </summary>
        [DataMember(Name = "DiagnosticInfos", EmitDefaultValue = false)]
        public List<DiagnosticInfo> DiagnosticInfos { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PublishResponse {\n");
            sb.Append("  ResponseHeader: ").Append(ResponseHeader).Append("\n");
            sb.Append("  SubscriptionId: ").Append(SubscriptionId).Append("\n");
            sb.Append("  AvailableSequenceNumbers: ").Append(AvailableSequenceNumbers).Append("\n");
            sb.Append("  MoreNotifications: ").Append(MoreNotifications).Append("\n");
            sb.Append("  NotificationMessage: ").Append(NotificationMessage).Append("\n");
            sb.Append("  Results: ").Append(Results).Append("\n");
            sb.Append("  DiagnosticInfos: ").Append(DiagnosticInfos).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // SubscriptionId (long) maximum
            if (this.SubscriptionId > (long)4294967295)
            {
                yield return new ValidationResult("Invalid value for SubscriptionId, must be a value less than or equal to 4294967295.", new [] { "SubscriptionId" });
            }

            // SubscriptionId (long) minimum
            if (this.SubscriptionId < (long)0)
            {
                yield return new ValidationResult("Invalid value for SubscriptionId, must be a value greater than or equal to 0.", new [] { "SubscriptionId" });
            }

            yield break;
        }
    }

}
