/*
 * OPC UA Web API
 *
 * Provides simple HTTPS based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 1.05.4
 * Contact: office@opcfoundation.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Opc.Ua.WebApi.Client.OpenAPIDateConverter;

namespace Opc.Ua.WebApi.Model
{
    /// <summary>
    /// ReadRequest
    /// </summary>
    [DataContract(Name = "ReadRequest")]
    public partial class ReadRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ReadRequest" /> class.
        /// </summary>
        /// <param name="requestHeader">requestHeader.</param>
        /// <param name="maxAge">maxAge (default to 0D).</param>
        /// <param name="timestampsToReturn">timestampsToReturn.</param>
        /// <param name="nodesToRead">nodesToRead.</param>
        public ReadRequest(RequestHeader requestHeader = default(RequestHeader), double maxAge = 0D, int timestampsToReturn = default(int), List<ReadValueId> nodesToRead = default(List<ReadValueId>))
        {
            this.RequestHeader = requestHeader;
            this.MaxAge = maxAge;
            this.TimestampsToReturn = timestampsToReturn;
            this.NodesToRead = nodesToRead;
        }

        /// <summary>
        /// Gets or Sets RequestHeader
        /// </summary>
        [DataMember(Name = "RequestHeader", EmitDefaultValue = false)]
        public RequestHeader RequestHeader { get; set; }

        /// <summary>
        /// Gets or Sets MaxAge
        /// </summary>
        [DataMember(Name = "MaxAge", EmitDefaultValue = false)]
        public double MaxAge { get; set; }

        /// <summary>
        /// Gets or Sets TimestampsToReturn
        /// </summary>
        [DataMember(Name = "TimestampsToReturn", EmitDefaultValue = false)]
        public int TimestampsToReturn { get; set; }

        /// <summary>
        /// Gets or Sets NodesToRead
        /// </summary>
        [DataMember(Name = "NodesToRead", EmitDefaultValue = false)]
        public List<ReadValueId> NodesToRead { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ReadRequest {\n");
            sb.Append("  RequestHeader: ").Append(RequestHeader).Append("\n");
            sb.Append("  MaxAge: ").Append(MaxAge).Append("\n");
            sb.Append("  TimestampsToReturn: ").Append(TimestampsToReturn).Append("\n");
            sb.Append("  NodesToRead: ").Append(NodesToRead).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
