/*
 * OPC UA Web API
 *
 * Provides simple HTTPS based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 1.05.4
 * Contact: office@opcfoundation.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Opc.Ua.WebApi.Client.OpenAPIDateConverter;

namespace Opc.Ua.WebApi.Model
{
    /// <summary>
    /// Defines StructureType
    /// </summary>
    public enum StructureType
    {
        /// <summary>
        /// Enum Structure for value: 0
        /// </summary>
        Structure = 0,

        /// <summary>
        /// Enum StructureWithOptionalFields for value: 1
        /// </summary>
        StructureWithOptionalFields = 1,

        /// <summary>
        /// Enum Union for value: 2
        /// </summary>
        Union = 2,

        /// <summary>
        /// Enum StructureWithSubtypedValues for value: 3
        /// </summary>
        StructureWithSubtypedValues = 3,

        /// <summary>
        /// Enum UnionWithSubtypedValues for value: 4
        /// </summary>
        UnionWithSubtypedValues = 4
    }

}
