/*
 * OPC UA Web API
 *
 * Provides simple HTTPS based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 1.05.4
 * Contact: office@opcfoundation.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Opc.Ua.WebApi.Client.FileParameter;
using OpenAPIDateConverter = Opc.Ua.WebApi.Client.OpenAPIDateConverter;

namespace Opc.Ua.WebApi.Model
{
    /// <summary>
    /// [Link to specification](https://reference.opcfoundation.org/v105/Core/docs/Part11/6.9.4/#6.9.4.1).
    /// </summary>
    [DataContract(Name = "UpdateEventDetails")]
    public partial class UpdateEventDetails : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UpdateEventDetails" /> class.
        /// </summary>
        /// <param name="nodeId">nodeId.</param>
        /// <param name="performInsertReplace">[Link to specification](https://reference.opcfoundation.org/v105/Core/docs/Part11/6.8)..</param>
        /// <param name="filter">filter.</param>
        /// <param name="eventData">eventData.</param>
        public UpdateEventDetails(string nodeId = default, int performInsertReplace = default, EventFilter filter = default, List<HistoryEventFieldList> eventData = default)
        {
            this.NodeId = nodeId;
            this.PerformInsertReplace = performInsertReplace;
            this.Filter = filter;
            this.EventData = eventData;
        }

        /// <summary>
        /// Gets or Sets NodeId
        /// </summary>
        [DataMember(Name = "NodeId", EmitDefaultValue = false)]
        public string NodeId { get; set; }

        /// <summary>
        /// [Link to specification](https://reference.opcfoundation.org/v105/Core/docs/Part11/6.8).
        /// </summary>
        /// <value>[Link to specification](https://reference.opcfoundation.org/v105/Core/docs/Part11/6.8).</value>
        [DataMember(Name = "PerformInsertReplace", EmitDefaultValue = false)]
        public int PerformInsertReplace { get; set; }

        /// <summary>
        /// Gets or Sets Filter
        /// </summary>
        [DataMember(Name = "Filter", EmitDefaultValue = false)]
        public EventFilter Filter { get; set; }

        /// <summary>
        /// Gets or Sets EventData
        /// </summary>
        [DataMember(Name = "EventData", EmitDefaultValue = false)]
        public List<HistoryEventFieldList> EventData { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class UpdateEventDetails {\n");
            sb.Append("  NodeId: ").Append(NodeId).Append("\n");
            sb.Append("  PerformInsertReplace: ").Append(PerformInsertReplace).Append("\n");
            sb.Append("  Filter: ").Append(Filter).Append("\n");
            sb.Append("  EventData: ").Append(EventData).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
