/*
 * OPC UA Web API
 *
 * Provides simple HTTPS based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 1.05.4
 * Contact: office@opcfoundation.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Opc.Ua.WebApi.Client.OpenAPIDateConverter;

namespace Opc.Ua.WebApi.Model
{
    /// <summary>
    /// UserTokenPolicy
    /// </summary>
    [DataContract(Name = "UserTokenPolicy")]
    public partial class UserTokenPolicy : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UserTokenPolicy" /> class.
        /// </summary>
        /// <param name="policyId">policyId.</param>
        /// <param name="tokenType">tokenType.</param>
        /// <param name="issuedTokenType">issuedTokenType.</param>
        /// <param name="issuerEndpointUrl">issuerEndpointUrl.</param>
        /// <param name="securityPolicyUri">securityPolicyUri.</param>
        public UserTokenPolicy(string policyId = default(string), int tokenType = default(int), string issuedTokenType = default(string), string issuerEndpointUrl = default(string), string securityPolicyUri = default(string))
        {
            this.PolicyId = policyId;
            this.TokenType = tokenType;
            this.IssuedTokenType = issuedTokenType;
            this.IssuerEndpointUrl = issuerEndpointUrl;
            this.SecurityPolicyUri = securityPolicyUri;
        }

        /// <summary>
        /// Gets or Sets PolicyId
        /// </summary>
        [DataMember(Name = "PolicyId", EmitDefaultValue = false)]
        public string PolicyId { get; set; }

        /// <summary>
        /// Gets or Sets TokenType
        /// </summary>
        [DataMember(Name = "TokenType", EmitDefaultValue = false)]
        public int TokenType { get; set; }

        /// <summary>
        /// Gets or Sets IssuedTokenType
        /// </summary>
        [DataMember(Name = "IssuedTokenType", EmitDefaultValue = false)]
        public string IssuedTokenType { get; set; }

        /// <summary>
        /// Gets or Sets IssuerEndpointUrl
        /// </summary>
        [DataMember(Name = "IssuerEndpointUrl", EmitDefaultValue = false)]
        public string IssuerEndpointUrl { get; set; }

        /// <summary>
        /// Gets or Sets SecurityPolicyUri
        /// </summary>
        [DataMember(Name = "SecurityPolicyUri", EmitDefaultValue = false)]
        public string SecurityPolicyUri { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class UserTokenPolicy {\n");
            sb.Append("  PolicyId: ").Append(PolicyId).Append("\n");
            sb.Append("  TokenType: ").Append(TokenType).Append("\n");
            sb.Append("  IssuedTokenType: ").Append(IssuedTokenType).Append("\n");
            sb.Append("  IssuerEndpointUrl: ").Append(IssuerEndpointUrl).Append("\n");
            sb.Append("  SecurityPolicyUri: ").Append(SecurityPolicyUri).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
